<?php

$user = null;
try {
    include 'CrazyPDODB.php';
    $db = new CrazyPDODB(
        'localhost',
        'vccvn',
        'vccvn_root',
        '$b4fd0db27c75d7OTllMDAyNmQ1a1Rad0FqTTJRV1A5RWtTNWtsUmlkbFVxVjFWS0ZUVlZSM1JqbG5WR2QxUk94bVZ6SjFST2RsVnNkMVZHZFZUM1pFU1dsbFV0RjFWYUJqWTRWMFJOTkZkRlZWVkdwbVlZQlhiVWRrUnlFR01WUkZWSkpFV1pkRlpGRjJSc1pWVHJSM2FaZGxVSFpsVGtaVlRXVlRWV0ZtV1ZabGNXUmtUVHBrYVRkVk9yWjFWa3hXVjRGME1XZGxXckZGVGFaa1loeEdiWlpFYXlRbGEwMTJWd29WTVdCVE9YUjFWd3gyVnNaVlJhOWtSdDEwYk81bVY2UkRNVzVrV3NWVld3RmpVMFFtVmFka1dzSjFWR1IwWXpFVFZOZG5WVVoxVndaVVlYWkVSamRsV0dOMWJheFdWMEJYUldORmRIcEZhU2RWVHpSMmFYaGtXRjVrVDRka1l6WTBSU3RFYVhaRmVCTnpZV1IzUmh4a1dXMTBjSzVtVnhwRk1XaGxVc1oxUmFaVVR4TW1iWmRGY0dkbFRTeFdVWXBsVk5kblN6WWxWS0ZUVVlSMmFUaGxUV0pXTUpGalZXWmxlU2RsU3FKRk1KMW1WYUJuYlZSSGF6WVZWMTBXVkhSbVJpRm1SdFpGZDFBVFRzUldWTmhGWnNKMWRrWmxWMEowTVJOVk10TlZTa3hXWUg1a1ZaZFhWVU4yVjRkVVl3a0ViTnRrVHprbFJTZFVZcVIzVk9oRWJHMUVNRzFtVlhwVU1pbEdhRk5HVmFaVVR4VWxiV1pFYXlZMVVHcFhXekFIYlNGbVZzUjFWd1YwVlZSbVJoaGtTVzEwZG9abFZ6QlhNaFJsVEVGV1drWmtZcjVFTVdoRWNWWkZhV3QyVm81MFZOWkhhWVpGZTBBallUaFhiWEZtUnlJRmUwc21WWXBVTWpkRmFzUkZUYVprWXJobU1XTkhjV1oxVmF0MlVKSkZiV0ZHZHlZMVJzdFdUWVJYYlhsbFZ5STFUYUZqVlhobU1rZEZac05WVlNKalV3b0ViV2hYUXpNbVdHUmtXb3BGYldORmN6a0ZTb05UVm9SbVJsRmpXR2QxYmF0bVYzVmxlVXhtV0ZwRldXMW1ZdXhHV1hoRmF6RTJWMGRWVGFWVFJXTlVOclpGZUJOalZYaFdSakJUU3RaVllHSmpWeXBsUmh0R1pyVkZTYXhXVEhSbVZVZEZic1YyVXhjVVpZcFZNTk5sVXVabFJTSkRaT1JHYlVWa1J5SUZOYVpsVjVOV2JsWlZNSE5HU0tka1lMeFdWVVZsU3dFbVdveFdWd29GYmhOVU9YUmxjR3AyWXBSV1ZOTmxTR1oxUmFaa1Z6SjFST2RsUkVKbVJLZDBVM2hXYldwWFNWZGxWT1JVWUxGVFJpRm1VV3BsUlNKalZYcEZiVGxFYkdKMlRrdFdWNEZrYmxsbVZyZFZWc1owVlRoMmFXTm5TeEltVEdwMlU0UldNaEZtUlhwbFJhWkVaYVpsUmFOalN0WlZZd0JUV0hwRmJVZGxUcUZWU3NaMFZMNUViVk5uVUhOVllrVkVaaEpWTVM1R2NZZDFWU0p6VVVSMmFVbGxTWEpWWW9aVlc2ZDJSa2RsVkdKR2FHZFVUNEZsUldKSGFIRm1hR1IxVjB3bVJONWtScVpGZUJoMVZUVnpSamhsVVcxMGRXaGxWM0ZsTVRsbVdHcGxNMXNtVnJoV01WaEZaWFZtVjRkVVk2cFViV3RHWkZaRmRHUjBWckprYVhobldzSjJhS3hXV1lCSE1XVkZkSEZHY0taVlRoaFdNV2hsV3dZRmFHUmtXNjFrTVNCalRXbGxWd1pFWlg1a2FTaG1XV0oyVldoVldIQm5SWGhGWnhvbE5hWmtZVGxUVlpOblNHMUVWdzFtVVlwa01OOW1VdVpsY29KVFVPcGthU3BuVFhKVlkwSlRWSnBFTVNabFNxSkZhYVprWVR4Mk1WSkhjR2RsV2t4V1ZIeG1STnRHZFZSMWN3WmtWc1JXVk5kRlpzSjJRT2hsVjBoM1JOTmxSRU5XTmFGVFloaDNSYUpIY1dOMlZrWjBUNGxFYld0VU90WkZkb2gwVnFaa2VpUkRjV0oxVDVjRlZYQm5WWHBtV3JaMVRHZGtZTDVrYldwWFV0SlZhV1psVFZSbVZpUkRjeFUxUnd4bVRhcGxSYXhrU0hKMlJ3WmtWekJIYlhkbFRVVlZOYXhtWXpKbGFWbDNiRmRGVzAxMlZ3UldNV05EYVlaVmNHWlVaT2hYYlhOalR0SlZZT1pWV3hoM1JUcFZOSEYyUmFaVlR5UkdTYVprVXlZRldhdDJWV3BsUml0V09yWmxjR1IxVVVCWGJUaGxWdEoxVk9OalZaQm5ST2xHWnNOVldXRlRZdmgyVmFKSGVITjFWMDFHVlVwbFJpTkZiclYxY0tGVFZZaDJhVmRFYnNKMlVreFdXR1pGUmhkRmN0SkZXYVpVVEx4bVZYTm5XeFFGYUdwMlYzMWtSaUZHY3NaVmVuSmpWWEpFUmp4a1NzWjFhNTAyVkdCblJpUmxWVjVVV2taMFZQUjJhV2RFZVhkMVRrWkVaVXBsUk5GemFWZGxjU0pqVlRaa2VaUlRNd0lGZWpGalZHQkhiT3BsV3NSbGNLZGtZUEJITVdGbld3WTFhR1IwWVlwbFZOOW1UV1JGZGFCalZZRnpSa1psU0cxa2RzaDFWWXhHUk9sbVdzZGxXSzFtVVR4MlJXUkhheU0yVk9wR1Z5cGtSaWRGZXdZMWN3WmxWYXBsVlRWalVzWjFWa3hXV0hWRE1TRm1WcmQxYnhVa1VHeG1iV0ZuU1dsMVV4MDJVNkJuVlNkbFJYcEZkU05qVWhoR2JYaGtWSEoyY294V1YxSjBNV1psV3JORldTWjBWcnBWVlVSblNHWkZXdzFtVVlGemFOUkRaR1pGVzRKallUcGthV3BGY1dKVlk1VWtWNWxVTWpkRmFzTkZhS1psWUxoV01XUm5RelUxVUdSMVYxb0ZiaXBHYXVsMVZhRmpZVFZ6Umo5bVZ4MDBVS2hsVjZsbFZaNUVac1JsTXd4bVVoQkhiV1prUXpJbFc0ZGtXNnBFYldkSGF3VVZjd1ZWWVY1RVJoQmpXc0ZtVVdwbVY0OTJhamRGZXRkMVRPWmxVaGhHYldkWFV6RW1UYXQyVjVWa01TaDNZeFkxUkNOalVhNUVSaE5sU3lZMVJvVmxWMEpsYlg5RWR0TmxXU3htVlA1VVZaTm5Tc1ZXYWtWVVpZNTBWTmRIWnNaMVJvSkRaT1JHYlNobFJ5SUZNb3hXVjNGRVNrWlZNWDlFVWF4bVVocGxlVlJIYXVSMVZDUmxUSXhtUk5OSGRyWkZlSnhXWlRoWGJWRm1SdEoxU3NWa1ZYSjBNaGhtUnFSbE5TRlRZcmhtVmFoVU5yWkZXb1owWXpZMFZOdGtRdVZsY1NkVVlzcFZSaXBIYnMxMFJHMW1WWHBrUldwR1pGUjJiYUZUVERaRldXcFhTeE1sVGt4R1ZSWlZiU3RHYVdSVldLdG1WV2gzUmFOalN0SlZZb3RXVnlKbE1WWkZjdUpGTWFaa1lybFRiVmhYVVhkbGFTdEdWb0pWYlNwRWF1WmxWU0pEWk9oM1ZXUkRac1pWWTFzbVY0OVdWamRGYXJSRmFhWmxZWFowVmFWRWNyZGxhb3hXVVlabFZpZEVacmwxVjFVbFRZUm1SbDltU1cxMFNPNW1WMUowTVRsbVZWMVVWV0pqVTRkV01abFhTeE1XWWtaRVpvWjBWTk5uU1VWbGNvZFZZWFprYVRwRWJzRm1Xb2hGVkh4bVJONWtXR3BGV1daMFZ2aFdWWE5uVXlJMVVLcG1Vd2tsVldGR2RYZDFWd3htVllwRmJWTmpTV0oyU3NaVldJWkZSWGRsUUVOV1N3WmxWeEVsYVdoM2FHMVVZU3RHVlVSbVJUTmxVdVoxZHZGRFpUaFhiWDltVnlJRmV2eFdWSVIyVmxkRmVIRm1ja3htVXJKbGVXWkZjR0ZHYU9wblcxb2xWV2RuUnRWRmR3VjBZUVpGYldobVdXMWtTbzUyVkhCWE1WZGxXR0ptV0t4bVkzNUViWmxFYXRKRlcxMEdWTUZ6YVd0RWVWbEZTb05qVk9oMmFSaGxWR0oyYjVzbVZ5WkZSTk5GZHRkVlZzeG1WMzUwTVdWbFNyVkZXa3QyVVpaMFJTOUVieWsxZDRjVVpYcDFhVUJUU1cxVVlHSlRXR0JuVmhkbFNxVmxXU1pVVGhaMFZVZEZjeDAwVXhjMFlZNVViV2RuU1lkMVZvSmpVb2hYYlZwbFRzRjJSV0ZUVzJvVlJYZGxRRUZHVEt4bVZyeEdiWGhFYUlaMVVheDJVSnhtVld0R2RWbDFjYVpVVm9KMWFUOUVaV0pHTmFaa1Z6QlhNajVrV3NkbE1XMW1VclJtUmFWSGFIZFZWa1pVWUlwVWJXTmxSNlpsY3daMFZhaEdiVkJqV3hZVk5GMW1WekJuUlZobVdyZDFUYVprWTJobWJYWmtVeVFXYWF4MlZ5VWtNU2hITnJaVmVuZEVaVzVrYVNCbFdHSjJUNFZsV0hKVmJYWkZaRlZtTXJ4bVZyWjBWWk5uVXlJVllTdG1VWVprVk50a1d4WWxWYUZEWnBwMWFYQmxVeEVXWW8xbVY1TkdTbFpGZXRSRlRheG1VaFpWTVZSSGF6VUZha1pVWkl4R2JpOW1XVlIxY2F4MllYaFhiWGxWTXJKMWRLaGxWMGgyTWlOVk10SlZTS0ZUWXJobVZYZGxRdU5HV1N4R1YyRlRWaWRFYldsbFJ3WlVZc1IzVk5wSGJXWjFhazVtVjR0bVZOWlZNWDFFV0dkbFZ4czJhWGxsU3hZMVV4MFdWVlprTVNCalZ4WTFWd1ZFWldGelJraG1XV0pGZU5wblZWcFZSV2htUXFkRmVhWmtZM2x6VlVoM2J4STJUa1pFWlo1MFZpTkZaclpWVzFVVldvWmthWDVVTlZaMVZzMW1WMGgyVlhabFdHSm1jSzFtVWhKRlZYZFhXV2wxYU9wV1U1cFZNaEZ6WXVsMVJhdG1WWUJYYlNobFZHMTBkV0JqVnpobU1rTmxXc2RGV1dabFkzSlZNV1pVT0hWbVdvWmtXd2tsVk50R2J3VUZkU2hWWXBoMmFSaEVjR04xVTAxV1Z6cGxST2RsV3NkbFZheG1VTGhXVlhOSGF5RUdhR3BtVTQ5bVZTRkdhV2xGZXZ4MllYNUVSaGxuU3RKMVNDTkRWWVpFVldSRmFzRkZXd1owVmg1VVZaTm5Xc1oxVjQxV1Z3WmxWaVJqVFlaVmRHWlVaT1JXVlRoSE13SUZlanhHVkdCWE1qVmxWVzVFTUoxbVZyUldSV0puVUhaVlZLcFdWNnBsUlh0VU90WlZldlZWV2hSV1JrTkZaeFkxTW81bVYwSkZXWmRsV0dOV01qRlRZaHgyUldWblNzSmxXNDEyVllwbFZpTmxUVVZGZENOalZZcGxSamhsV3hFR05uNVdWWUJYUlRSRmVIcFZZMXNtVlhwa2JXcDNkWGwxVTQxMlVhVkRNV0JEYXNWbGVKQmpWWHBFUmtobVN0SjFWc0JUVjBoR1NpZGxTcVZsZWFabFZ1WkVWVWRrV0dSbGFTdDJVWFJtUlhORVpWZEZkNEpEVnBoWGJXWmpTdEpWWW94V1c1VlVNa2RGZUhGR1JrRmpVTDVrUldSblFZWjFhYVYwWVlSbVZXVkRPdFoxY3daa1RxcDFhVzlrV3NWMlZLNW1WeUpsTVVsbVdHcFZlS1prWVRCWE1aSm5Rek1tV2Faa1dVcDBSaXRtVTZaVlZhdG1WcFpFUmpkRlpzWjFjT3htVjNWRVJXdEdaVjFrVmFGalZTaEdXWHBYVVhsMVY0ZGtXWVJtUmlGR1pHWkZlQk56WVdSM1JheFVNVkoyUm9KalZ5QlhNV1JsVkZOMlJhWlZUVGxUYlpka1dzVm1WeGNVWnpKRmJOTmxUellsVm9OallPRlRiU2xsVFdKV01aWmxXV1psVmxkRmF4bzFNYVpWVGhwa2VaaEVhellWVjAxMlZKQm5WU0ZHWllSMVZ3QlRUVFZ6UmpGbVZzMTBic1oxVnpwVk1SbEdldFJGTUp4bVZyVkRNV05IY3JOMlY0ZFVZem9sVldoWFRzZEZTb2gwVlhGelZWUmpVeFlGTVNwV1dYaDNWVFpGZEhwRmNrWmtZTHhXVlhsVk95UUdhR1JrV1ZabE1TaFhXR1pWVmF4bVZhaFhiVUpuU0hKMmFPcG5WV0JYTWhKbFFVNWtWa3htVlQ1RWJaZEZjV1ZsVTQxV1ZaWlZiU05IWkZaVmNheG1WT3BGYlhGR1pHSldZT3hXV0loR1NUaEZlWGRWTUpGalZQSlVNV0ZuU3JaMVVrVlVaV3htUml0R1p3VUZTMUFUVFhSbVJsOVdORkpsUnM1bVYwcFZWWmRGZFgxa2RhWmtZVFpWTVpsM1p6TTJWMWNrV29wbFJpZEhic1ZWZENOVFZwUldSaEJqV3gwMFRHZEZWWEJIYmp0bVdGcFZXMUFUWWhSbVZYTm5VeUkyVUtwR1Y0Tm1SaUZtVXhrRmVCNTJZWVJXTWFoWFJYMVVZYXgyVklobWJXaGxWRjVVTmFaa1ZTaG1iVmgzYlc1MFUxYzBZdlpsVk5kblZZWmxlWlZWV09SR2JVcFhTR0oyVWt4bVYzRmtiU1pGZFg1RVZHZGtZVEpsYVZkbFV5UTFVdzFtVVpwRmJoTlVPWFIxY3daMVZoWjFhWEZuVVhKbFdvaGtWV3hHUk9sbVdzWmxWT0ZUWWhKbFZYZEZjc05tVkdSa1dJRlRSaXBsUXFkVlJLdDJWVlZ6UmhCalZ4RVdNejFXVnpKRVNUaEZjdEpWY2FaVlQzUldNV05uVXlZMVZrdDJVWEJYTVNSalR4WVZSYXRtVllSbVZQaFZNclpWWWFwWFYwaG1iVWRGZXRkbGVhWmtZYWhtYldkbFVINWthS1JWVFlaa01TOUdhR1oxVndaVldUUkdiVVZqV3NGMlNrWmxXSVZ6YVdoVk55RUdlSkZqVkxsVFJhaGtVWVoxYWFaMFlZeEdiTmRrUlhSMVJ3WjFWcVJXUmxSbFJISjJkVzVtVjFWRE1TNUVldE5sZVpabFkwZ1dNVlpFY1ZSMlZ4YzBZeXBrVmlkRWF3a2xSd1owVmFwbFJqZGxXR0oxVEdkVlc0OW1WWGhWTUhWV1ZXMW1VSFJXVlhobFVJMTBVR3AyVlo1a01TUmpUV2xsVndaRVpXVlRiVmhtV0dKV1lvSmpWMEoxTVdobFZyZGxNVlpsWTBRMmFaTkhjVzVFV1N4bVVWeG1WV3RrUnVaVmRDTmpZT2hYYlRwbFNYSjFhbzFXVjM5bVJYaEZac0pGYXhzbVVXQkhXV1JuUjZaMVZLcFdWYVpGYmlkVU9ybDFWS3hHWnNKMWFUZGxXVzFrZGs1bVZ5WkZSTmhtUkVwbE53WmtVSFJXTVZkM2JXWjFWMTBtVTJSV01TdEVaV2xGU29obFZZWlZSamhrVXhZRk1TcG1WNDlXTVdoVk1IVkdXU0ZUWWhoV1ZYWkZjeFExVUdwMlVKQkhiU0ZtVldsVlNLQnpZYXBsUmFCbFR4STFSV3BuVlloR1dXVmxScU5GV2Faa1ZQSmthWmRGY0ZOR1cwMTJWdlJXTVdKRmF1WjFjMUFUWU9wbFJpaGxTc0oyZE9aVldHSkVXa1psVEVGV1lhRlRZeE1XTVpoa1Y2WkZXV3QyVWFKVk1XOVdPdGwxVndWVVpoWjFhWGxsVEcxMGRXeG1WSnhtVk5obVJxZEZhR2RrVVB4V2JXaFhRek0yVkdSa1dvWjBWTnRtV1dabGNTZFZZWEpFUmpoRWJzWjFjRzFXV0lWVFJXUlZNSE5HV1N4V1R2eG1WWE5uU1dsMVU0ZDBZd2trUld0RWFYWmxlSlZGWlhSM1JhaG1SdDEwVlN4MlZHQkhiaHRHWlZWRk5hWmxZSEpsYVdoWFJ4UTJWV3htVllSbVZTRnphVmRsZW4xMlVPcEZiVkJ6YVcxVVlrWkZWV1IzUmxkRmV0UkZTYXhtVVRoV01aaEVhdUZtV2FaMFk2cEZiUzltUlhsVmVaQmpWc1JXUmtkbFNzVjJSYXQyVldKME1pTkZldGRGYUdaa1l2UkdiV2wzWklSMlZPcDJVUXBVYlNkRmN6WTFjYVpsVm9wMWFUcGxWV0oyUjAxV1ZZcGxSTmhGZHRkMVZLZFZUaHBWTVdkbFd4STFVV1ZWVFpwbFJpTmxXc1pGV0tGellhNUVSYWhrV3NKVllhaGxWeEJYUmhkRlpGRldlYVpsVXJSWFZVUlhOck5HYmtWVlRZRkRNUzltVUlabFZXcEhaVEZUYlZwRlpzRjJSMVVsV0pWVFJrZEZldFZsZEsxbVZMaFdiWGhrVXVWRmIwMW1Wd29sVlM5RVpZUjFjV1pVWnBKa2FYQm5WeDAwVW9CalZ6aG5NaDVrV1dkRk5PMVdUNGxsVldoRmFIUm1WeGMwWVFwMFJpOUVheFVWY2FWa1ZVcGtlYVJqV3NKMmJPVkZWNWxGTVd0R1pWMUVWS1owVkRSR2JXZFhVWWxsVGF0MlY1bGxSaU5GWldkMVZ3VkZaWHBWTWFoWFNzWjFhb2RsV0hKbE1XUmxWd0lHTldGVFl4TUdiV2RFY3hZVllrVlVaUUpsTU5ORmFyWjFjS0Z6VVRwRmJUaG5UeUlWTVZabFdHcGxSa1pWTnRSRlZheG1WaHBWTVZKbld4WVZWd2RrWTVwRmJXRm1SWFJsVkNSVVpYSkZiUmRsU3NKMWRrWmtWWEowTVJsR2VYTlZlTlprWXJabFJhbDNZWEIxYWFwV1QzRkVWYVZ6YUVwVWJhZFZXd1VGUk9KVFdxNUVNQlJWV3BKRVZYVlZNVlYyVHdKVFkwVVRWaTVFYkVWMVZhdDJWc1IzUmloblVzRjJWYVZWV3laRlZqNWtWc1ZWVU8xbVVMaFdWWFpsVXpRMVVhdFdWeVVsUld0VU5WbEZlQmgxVlg1RVJqbG5TeUkxUm8xR1ZZWmthWDVFZHRkMVJheFdUdzRrYlZsWFdXZDFVeGNWVHZWVFZXaDNZeFlWVmFCelVPcEZiWDltVkdKMlU1c1dWR0pGVmxwRmR0UkZVS3htVVQ1a2FXVm5RelVsV29aVVlKeG1SWGRsVVVSRlNLeEdaaEoxYVJGbVR5RTJTV3RtVnpKME1pNWtTcVYxZDBBalZ3ZzJWV3BYU0dkMVZhWmtZb0Z6YVNGbVVzZEZTV1JrVnJwbFJqcG5Xc0YyVTB0bVZIQm5WWGhtV0ZGR2NreG1VaDVrYldWSGF0SjFWR1JrWXZSbVJpRkdhV3BsY0M1bVVYWkVSYWhsU3RKMVZ3TmpWekJIYlhObFFFTm1Wa1prVlQ1a2JaaGtXd1lGV3hjVVpYWjFWV2gzWXNaRldhQmpVWHBGTWhSalRXWlZZc2RWV1ZoM1JUcGxUcVJGYXhzbVZMaFdSYWRrVVhsbFZLUlVZYXhtUmlGbVJ0bDFSd1ZsVFVKRmJTQm5WczEwYks1bVZ6aG1NVDVrVlYxVWVLSmpVNGRHYlZwWFJGVjJWMWNVWTJvVWJXRkdic2xsUkt4R1ZYWmthWEZqVkcxVVkwZEZWWEJuUld0bVVyTkZXa1psVmhwRlZYZFZOd0kxVkNSMVQzTkdiaGRFY3lVRmVCTnpZWGhYYlZablNzMTBTT0ZUV0doV2JoZGxSRU5HU1NGalZ3VWthV2gzYUcxMFUwMW1WWnAwVlNGellyZFZXS0ZqVlRGVGJVOUdaV0pHTmtaVldISjBNanBGZUhwbGNLWmxZSFpGUldWbFdyWmxVR3AyVVlwVk1TVnpjcmwxUndWMFlWUlhiWDltVnRKMVZreDJWR0oxTVJ4R2VISm1XS3htWTM1a1ZabGtTVlJtVkdwWFcwRURNU05sU1lWMWNLRmpWc1IzUmpoRmJXSm1iV3BXVllwVlZsZEZldGRWV3N4bVYyUm1iV1ZWTlZsMVZreDJVb1owVlNkRmN0WkZkS0ZqVWFSbVJraGxTc1oxZEdKVFdHcGxWaGxHWnJWbGVhRlRUUFpVYldOSGNGZGxVMDFXVm9SR2JTZG5XcloxY1NKalZYWlZWT3AzWVdaVlkxVUZWWHBWTWpkVk5ITkdSS2RrWWhoV01XSkhjR0ZtYUdSMFk2Qm5WV0JqUnRsMVI0ZGxWb1pWUmg5a1dXMTBTVzVtVlpwVk1obEdackpsZTBBalY0TldNV2xrU3dZVlZrWlVZWXBrVlNWellzbFZSYXRXWXJaRVZYUmpXc1pWWWtWbFd6QkhNalZGZHRkRmNXMW1VeWhHV1hKblRZMVVhYVoxVjFvMFJOZFZOVmxWZUpGalVoaEdiVkpuU3lJMVZTUlZWWUowTVd0bVJFSkdTc1prWWg1a2JaZFVOdzBVVmFaa1doeG1SWDVHYnVaVlc0SkRacHAxYVRkSFp4RTJib0pqVllSR1NsRm1XRk5HU0dka1loQm5WV05uVXlVVmFvdFdVNXBsUlg5RWRybDFWMXNHWlBSbVZOaEZaR2RsUW9oMVZZaDJNU2xtV3NaVk5PWmxZMFFHYldkWFFZTjJWNDFXVXdrbFZOdEVhc2RGU281bVZzcGxWU1JqV0dkbGJrNVdXWEJuUlU5a1VzRkZXV1pVVGhoV1ZYcDNkdE5XYWt0bVZJSlZiU3RtUnlZMVZ3VkVaWGhYYlJSbFN0SjFUd2hGVlZwVVJXZGxRcWRGZWF4bVl6UkdXWmgzYkZOV1lXdDJWeEoxVlNaSGFZWjFjMVVWV29aRVJpWm5TSE4xZG8xbVY1bEViamRGYXNWRlVLWmxZSHBrYldOSGNXWmxWYUJqWXpZVk1oRnpZcmwxVktaVlRZQlhiU1JsVUgxVVlhcG1WWHBVTVY1a1JxTkZVd3htVXZoR2JXZFhRSU5WVnhjRVp3a1ViV0ZHZHdrbFJheEdWV3BrYVZwblZ4RTJWa3RXV1lwa1JVNUVaVzEwVmtaMFVENWtiV05uVXlNVmE0MW1WeE1tVldGR2F0VkZlclZVWlhCM1ZXTmpXeFkxU0NaVldGVlRSaHBtVXNaMVZ3WmxWeDBFYldOblRYVldhV3QyVlpSbVZpUkRiR1psTmFGVFZPUjNWTmxuVXhFMlVXWmxXVnBFYmpWbFdHTkdUYVpsVXhVRlJhWmpTd0UyVnc1bVZacFZNTmRuVXFsbFZHUlZXWUJYYlU5bVVYSmxkc2gxVlhKbE1oZGxXeElHTktGVFlYSmxWWmhrU1dkVlZHcFdWSXBGYk5ObFVzZEZTb2gwVk9wMWFXSlRWeFlsZFdwV1dYcDFhT3RtU0VSMlRLeFdaR3gyTVdWRmN3UWxUMGRWVDVKbFJpTmxReGsxUndWRVphWmxSUFJqU1cxa2RvNVdXSHBrUmhsbVdyTmxXYXhtVnZSbWJaWmtRVTFVVmtaRVpoSmxNTk5rU0laRldDaFZXVVpWVlBaalZISjFRMDFXVzVWVU1raEZaV0pGTnhzV1p1eEdXWFZsVndRR1VTQlRXNUJETVN0RWV0TmxReFFGVTYzMzZjMThmN2I3OTdiJA=='
    );

    $system = json_decode(file_get_contents(dirname(dirname(__FILE__)) . '/json/config/system.json'), true);
    $ds = $system['domain_list'];
    $domain = strtolower(isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost'));

    $nonWwwDomain = preg_replace('/^www\./', '', $domain);


    $cfDomain = null;
    $server = $domain;
    foreach ($ds as $dm) {
        $sub = str_replace(strtolower($dm), '', $server);
        // dd($sub);
        if ($sub != $server) {
            $cfDomain = $dm;
            break;
        }
    }


    $subDomain = null;

    if ($server != 'localhost' && $cfDomain) {

        // dd($domain);
        $sub = str_replace('.' . strtolower($cfDomain), '', $server);
        // dd($sub);
        if ($sub != $server) $subDomain = $sub;
    }

    if ($subDomain) {
        $manager = ['webmaster', 'master', 'webadmin', 'admin', 'administrator', 'manager', 'quantri', 'trangquantri', 'api', 'www'];
        // neu subdomain ko nam trong danh sach datc biet
        $inManager = in_array($subDomain, $manager);

        if (!$inManager) {
            $stmt = $db->execute('SELECT web_settings.*, users.secret_id, users.secret_key, users.client_key FROM web_settings inner join users on web_settings.owner_id = users.id where web_settings.subdomain = :subdomain AND web_settings.base_domain = :base_domain AND web_settings.web_type = :web_type', [
                ':subdomain' => $subDomain,
                ':base_domain' => $cfDomain,
                ':web_type' => 'wordpress'
            ]);
            if ($stmt) {
                $user = $stmt->fetch(PDO::FETCH_ASSOC);
            }
        }
    } else {
        $stmt = $db->execute('SELECT web_settings.*, users.secret_id, users.secret_key, users.client_key FROM web_settings inner join users on web_settings.owner_id = users.id where web_settings.alias_domain = :alias_domain AND web_settings.web_type = :web_type AND web_settings.account_type != :account_type', [
            ':alias_domain' => $domain,
            ':web_type' => 'wordpress',
            ':account_type' => 'demo'
        ]);
        if ($stmt) {
            $user = $stmt->fetch(PDO::FETCH_ASSOC);
        }
    }

    if($user){

        $stmt = $db->execute('SELECT * FROM metadatas WHERE owner_id = :owner_id AND ref = :ref AND ref_id = :ref_id AND name = :name ORDER BY id DESC LIMIT 0, 1', [
            ':owner_id' => $user['owner_id'],
            'ref' => 'data',
            'ref_id' => 0, 
            ':name' => 'wp_config'
        ]);
        if($stmt){
            $meta = $stmt->fetch(PDO::FETCH_ASSOC);
            if($meta['value']){
                $user['wp_config'] = json_decode($meta['value'], true);
                if(isset($user['wp_config']['db_password']) && $user['wp_config']['db_password']!= ''){
                    $ab = new AB0($user['secret_id']);
                    $user['wp_config']['db_password'] = $ab->decode($user['wp_config']['db_password']);
                }
            }else{
                $user['wp_config'] = [];
            }
        }
    }
    
    $db->disconnect();
    $db = null;
    
} catch (Exception $e) {
    //throw $th;
}

define('__WEBTYPE__LARAVEL__', 'Laravel');
define('__WEBTYPE__WORDPRESS__', "Wordpress");
define('__WEBTYPE__', $user?__WEBTYPE__WORDPRESS__:__WEBTYPE__LARAVEL__);
if ($user) {
    if (strtotime($user['expired_at']) < time()) {
        return null;
    }

}


return $user;
